### ISSUE TITLE
MAC and URL only?

### ISSUE THREAD

**Issue by Chris230291** [erkexzcx/stalkerhek#22]
Hello. is it possible to use this with accounts that are URL and MAC address only?

Thanks,
Chris

**Comment by rockydares** [comment]
Yes it is possible. Read [this.](https://github.com/erkexzcx/stalkerhek/issues/21)

**Comment by Chris230291** [comment]
Hello. I saw that after making this post so I just used other details since it needs something in the config.
I am getting error though `2021/08/05 21:41:15 main.go:30: invalid character '<' looking for beginning of value
exit status 1`

**Comment by rockydares** [comment]
Put 0 in the value of other details, delete username and password field or keep them blank. For sn put `DC521EE1C00B2`. 
Invalid character '<' may show because of wrong stalker portal address. [Use this app](https://play.google.com/store/apps/details?id=app.greyshirts.sslcapture) while connecting to Stbemu of ott navigator and capture portal address if it is 'stalker_portal/server/load.php' or 'server/load.php' or whatever (pic for example). 
![IMG_20210806_093317](https://user-images.githubusercontent.com/66517282/128454271-09ba37f7-7ca8-4a26-81ee-3aab0dd8bb6c.jpg)

**Comment by Chris230291** [comment]
Thanks for the reply. The URL matches what I was already using. I wonder if this only works with certain stalker accounts? I've tried several and all give me the same error.

**Comment by Chris230291** [comment]
I am not sure where you are getting the accounts from, but is it possible to send me a known working config?

**Comment by rockydares** [comment]
It is not possible to send you a working config because the token would be already expired. But I can show you an example config here, or you can send me (rockydares223@gmail.com) the host and mac you're trying to log into. I'll check for you

Example config
![IMG_20210806_220355](https://user-images.githubusercontent.com/66517282/128542910-d914f7f7-d124-46c1-ae70-4efeb75615fd.jpg)

**Comment by Chris230291** [comment]
Thanks for the reply.
I still get the error though.
I tried the following settings...

```
portal:
  model: MAG254
  serial_number: 0F62DB185C000
  device_id: 0
  device_id2: 0
  signature: 0
  mac: <MAC>
  url: <URL>
  time_zone: Europe/London
  token: 0

hls:
  enabled: true
  bind: 0.0.0.0:9999

proxy:
  enabled: false
  bind: 0.0.0.0:8888
  rewrite: false # EXPERIMENTAL! see https://github.com/erkexzcx/stalkerhek/pull/12#issue-607960283
```

I wonder if its the token? I don't have one so I set it to 0.
I've emailed you with the credentials I am trying.
